/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IStargatePool,
  IStargatePoolInterface,
} from "../../../../contracts/interfaces/layerzero/IStargatePool";

const _abi = [
  {
    inputs: [],
    name: "token",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IStargatePool__factory {
  static readonly abi = _abi;
  static createInterface(): IStargatePoolInterface {
    return new utils.Interface(_abi) as IStargatePoolInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IStargatePool {
    return new Contract(address, _abi, signerOrProvider) as IStargatePool;
  }
}
