/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumber, Signer, utils } from "ethers";
import type { EventFragment } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface IBlockScopeVestingInterface extends utils.Interface {
  functions: {};

  events: {
    "TokensClaimed(address,uint256)": EventFragment;
    "TokensVested(address,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "TokensClaimed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TokensVested"): EventFragment;
}

export interface TokensClaimedEventObject {
  beneficiary: string;
  amount: BigNumber;
}
export type TokensClaimedEvent = TypedEvent<
  [string, BigNumber],
  TokensClaimedEventObject
>;

export type TokensClaimedEventFilter = TypedEventFilter<TokensClaimedEvent>;

export interface TokensVestedEventObject {
  beneficiary: string;
  amount: BigNumber;
  releaseTime: BigNumber;
}
export type TokensVestedEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  TokensVestedEventObject
>;

export type TokensVestedEventFilter = TypedEventFilter<TokensVestedEvent>;

export interface IBlockScopeVesting extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IBlockScopeVestingInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {};

  callStatic: {};

  filters: {
    "TokensClaimed(address,uint256)"(
      beneficiary?: PromiseOrValue<string> | null,
      amount?: null
    ): TokensClaimedEventFilter;
    TokensClaimed(
      beneficiary?: PromiseOrValue<string> | null,
      amount?: null
    ): TokensClaimedEventFilter;

    "TokensVested(address,uint256,uint256)"(
      beneficiary?: PromiseOrValue<string> | null,
      amount?: null,
      releaseTime?: null
    ): TokensVestedEventFilter;
    TokensVested(
      beneficiary?: PromiseOrValue<string> | null,
      amount?: null,
      releaseTime?: null
    ): TokensVestedEventFilter;
  };

  estimateGas: {};

  populateTransaction: {};
}
