/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as oracles from "./oracles";
export type { oracles };
export type { IAtomicSwap } from "./IAtomicSwap";
export type { IInterchainSwap } from "./IInterchainSwap";
export type { IOwnablePausable } from "./IOwnablePausable";
export type { ISideOracle } from "./ISideOracle";
