/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../common";

export interface IStargateRouterETHInterface extends utils.Interface {
  functions: {
    "addLiquidityETH()": FunctionFragment;
    "swapETH(uint16,address,bytes,uint256,uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "addLiquidityETH" | "swapETH"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addLiquidityETH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "swapETH",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "addLiquidityETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "swapETH", data: BytesLike): Result;

  events: {};
}

export interface IStargateRouterETH extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IStargateRouterETHInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addLiquidityETH(
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    swapETH(
      dstChainId: PromiseOrValue<BigNumberish>,
      refundAddress: PromiseOrValue<string>,
      to: PromiseOrValue<BytesLike>,
      amountLD: PromiseOrValue<BigNumberish>,
      minAmountLD: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  addLiquidityETH(
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  swapETH(
    dstChainId: PromiseOrValue<BigNumberish>,
    refundAddress: PromiseOrValue<string>,
    to: PromiseOrValue<BytesLike>,
    amountLD: PromiseOrValue<BigNumberish>,
    minAmountLD: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    addLiquidityETH(overrides?: CallOverrides): Promise<void>;

    swapETH(
      dstChainId: PromiseOrValue<BigNumberish>,
      refundAddress: PromiseOrValue<string>,
      to: PromiseOrValue<BytesLike>,
      amountLD: PromiseOrValue<BigNumberish>,
      minAmountLD: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    addLiquidityETH(
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    swapETH(
      dstChainId: PromiseOrValue<BigNumberish>,
      refundAddress: PromiseOrValue<string>,
      to: PromiseOrValue<BytesLike>,
      amountLD: PromiseOrValue<BigNumberish>,
      minAmountLD: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addLiquidityETH(
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    swapETH(
      dstChainId: PromiseOrValue<BigNumberish>,
      refundAddress: PromiseOrValue<string>,
      to: PromiseOrValue<BytesLike>,
      amountLD: PromiseOrValue<BigNumberish>,
      minAmountLD: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
