/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IAtomicSwap,
  IAtomicSwapInterface,
} from "../../../contracts/interfaces/IAtomicSwap";

const _abi = [
  {
    inputs: [],
    name: "AlreadyCompleted",
    type: "error",
  },
  {
    inputs: [],
    name: "AlreadyExistPool",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidTokenPair",
    type: "error",
  },
  {
    inputs: [],
    name: "NoPermissionToCancel",
    type: "error",
  },
  {
    inputs: [],
    name: "NoPermissionToTake",
    type: "error",
  },
  {
    inputs: [],
    name: "NonExistPool",
    type: "error",
  },
  {
    inputs: [],
    name: "NotAllowedAmount",
    type: "error",
  },
  {
    inputs: [],
    name: "NotOwnerOfToken",
    type: "error",
  },
  {
    inputs: [],
    name: "ZeroTokenAddress",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "id",
        type: "bytes32",
      },
    ],
    name: "AtomicSwapOrderCanceled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "id",
        type: "bytes32",
      },
    ],
    name: "AtomicSwapOrderCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "maker",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "taker",
        type: "address",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "id",
        type: "bytes32",
      },
    ],
    name: "AtomicSwapOrderTook",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "payer",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "daoShare",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "burned",
        type: "uint256",
      },
    ],
    name: "PaymentReceived",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint16",
        name: "_srcChainId",
        type: "uint16",
      },
      {
        internalType: "bytes",
        name: "_srcAddress",
        type: "bytes",
      },
      {
        internalType: "uint64",
        name: "_nonce",
        type: "uint64",
      },
      {
        internalType: "bytes",
        name: "_payload",
        type: "bytes",
      },
    ],
    name: "onReceivePacket",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IAtomicSwap__factory {
  static readonly abi = _abi;
  static createInterface(): IAtomicSwapInterface {
    return new utils.Interface(_abi) as IAtomicSwapInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IAtomicSwap {
    return new Contract(address, _abi, signerOrProvider) as IAtomicSwap;
  }
}
