/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IInterchainSwap,
  IInterchainSwapInterface,
} from "../../../contracts/interfaces/IInterchainSwap";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "payer",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "daoShare",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "burned",
        type: "uint256",
      },
    ],
    name: "PaymentReceived",
    type: "event",
  },
] as const;

export class IInterchainSwap__factory {
  static readonly abi = _abi;
  static createInterface(): IInterchainSwapInterface {
    return new utils.Interface(_abi) as IInterchainSwapInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IInterchainSwap {
    return new Contract(address, _abi, signerOrProvider) as IInterchainSwap;
  }
}
