/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ISideOracle,
  ISideOracleInterface,
} from "../../../contracts/interfaces/ISideOracle";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
    ],
    name: "getPrice",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ISideOracle__factory {
  static readonly abi = _abi;
  static createInterface(): ISideOracleInterface {
    return new utils.Interface(_abi) as ISideOracleInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISideOracle {
    return new Contract(address, _abi, signerOrProvider) as ISideOracle;
  }
}
